variables:
  PROJECT-ONE-DEV: 988
  PROJECT-ONE-QA: 2919
  PROJECT-ONE-INT: 2922
  PROJECT-ONE-PROD: 4182
  PROJECT-ONE_WIKI_RELEASE_NOTES_PAGE_ID: 45794
  PROJECT-ONE-BUILD-DEFINITION-ID: 3922
  PROJECT-TWO-DEV: 3116
  PROJECT-TWO-QA: 3117
  PROJECT-TWO-INT: 3119
  PROJECT-TWO-PROD: 4845
  PROJECT-TWO_WIKI_RELEASE_NOTES_PAGE_ID: 66130
  PROJECT-TWO-BUILD-DEFINITION-ID: 7780
  PROJECT-THREE-DEV: 4608
  PROJECT-THREE-QA: 4609
  PROJECT-THREE-INT: 4610
  PROJECT-THREE-PROD: 5013
  PROJECT-THREE_WIKI_RELEASE_NOTES_PAGE_ID: 71964
  PROJECT-THREE-BUILD-DEFINITION-ID: 7310
  NODE_VERSION: 14.x
